[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
| migrations
)
'''

[tool.isort]
profile = "black"
extend_skip = "migrations"
lines_between_types = 1
lines_after_imports = 2
