# Generated by Django 4.2.11 on 2024-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="credit",
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
