# Generated by Django 4.2.11 on 2024-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursepage_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='under_process',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
