# Generated by Django 4.2.11 on 2024-03-18 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="logo",
        ),
    ]
