# Generated by Django 4.2.11 on 2024-05-08 10:38

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_program_code_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='home.department'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='program',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='home.program'),
        ),
    ]
