# Generated by Django 4.2.11 on 2024-05-08 11:05

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursepage_credit'),
        ('home', '0007_alter_program_department_alter_semester_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=modelcluster.fields.ParentalManyToManyField(to='course.coursepage'),
        ),
    ]
